Ratelimit
NREL/engage pull request #159
Opened 2024-04-18 20:35 UTC by jeisenman23

This PR rate limits the map box token, ensuring we don't exceed the free tier. It also notifies the team when the token has been used 40,000+ times (where the free tier limit is 50,000).

2024-04-18 21:04 UTC, jmorrisnrel commented on calliope_app/api/migrations/0065_requestratelimit.py
We already have a migration 0065 in the dev environment from another feature branch. #156 

You'll need to rebase your branch from dev and remake the migration file so it becomes 0066 and depends on the existing 0065.

2024-04-18 21:04 UTC, jmorrisnrel commented on calliope_app/api/views/configuration.py
> +    if limit.total == 40000 and limit.total % 100 == 0 and limit.total < 50000:
`limit.total >= 40000` ?

2024-04-18 21:14 UTC, jgu2 requested changes

2024-04-18 21:14 UTC, jgu2 commented on calliope_app/client/views/configuration.py
> +    logger.info(f"Session Stuff: {request.user}")
Create meaningful logs. Or should the `logger.info` be removed (including a couple of other `logger.info` added below), are they used for development and debugging?

2024-04-18 21:14 UTC, jgu2 commented on calliope_app/api/views/configuration.py
> +                subject="NREL ENGAGE NOTIFICATION",
Let's use `subject="Engage Alert - Mapbox"`. Same below.

2024-04-18 21:14 UTC, jgu2 commented on calliope_app/api/views/configuration.py
> +    if limit <= 50000:
should it be `limit >= 50000`?

2024-04-18 21:16 UTC, jmorrisnrel commented on calliope_app/calliope_app/settings/local.py
> +EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
This is for the local environment and I believe lets us test emails on local by dumping them directly to console

2024-04-24 14:56 UTC, jeisenman23 commented on calliope_app/api/views/configuration.py
> +    if limit <= 50000:
Agreed, I reversed the inequality

2024-04-24 15:01 UTC, jeisenman23 commented on calliope_app/api/views/configuration.py
> +    if limit <= 50000:
This is for testing purposes, that the emails go through... We will reverse in final PR

2024-04-24 19:42 UTC, jeisenman23 commented on calliope_app/api/views/configuration.py
> +    id = int(f"{year}{month}")
I think this version is better though, since the id creates uniqueness and explainability. Incrementing by one only creates uniqueness, so why not both?

2024-04-29 18:37 UTC, jeisenman23 commented on calliope_app/api/views/configuration.py
> +    id = int(f"{year}{month}")
This will take some explaining. The goal of this ratelimitting is to limit by IP to 1000 per day, and 10 per minute. We also want to keep track of, on each day, how many times the token has been called and by whom, for a certain month. So I created a table that keeps track of just that. Viz, for April, I have called the token 21 times. 
<img width="658" alt="image" src="https://github.com/NREL/engage/assets/157855136/b3445139-e39c-4476-a29d-67665027f4d7">
If a second user were to hit the API, their information would be added to the dictionary and the sum would increment.

2024-04-30 23:06 UTC, jgu2 approved these changes
Reviewed via demo, great work!

2024-04-30 23:06 UTC, merged