solver
NREL/engage pull request #183
Opened 2024-06-04 19:56 UTC by jeisenman23

This PR removes the GLPK solver and replaces it with the CBC solver.

2024-06-04 22:10 UTC, jgu2 commented
Great work, CBC solver testing works at my local.

One more thing:

Update the Sphinx documentation as well, remove GLPK info and add CBC.

@jeisenman23

2024-06-06 21:03 UTC, jeisenman23 commented on calliope_app/compose/Dockerfile
> +    curl \
Resolved

2024-06-10 21:30 UTC, jeisenman23 commented
> Great work, CBC solver testing works at my local.
> 
> One more thing:
> 
> Update the Sphinx documentation as well, remove GLPK info and add CBC. - https://github.com/NREL/engage/tree/dev/docs/sources
> 
> @jeisenman23

Done

2024-06-11 21:10 UTC, jgu2 commented
calliope_app.api.fixtures.admin_run_parameters.json, rename `glpk` to `cbc`.

2024-06-11 21:37 UTC, jgu2 requested changes
Previous work got lost when doing PR merges, need to check the logs and revert back.

2024-06-11 21:37 UTC, jgu2 commented on calliope_app/api/fixtures/sample_scenario_param.json
> -      "value": "glpk",
It looks like this record got deleted.

Would this `glpk` be changed to `cbc`?

Rename the following `pk` number back.

2024-06-25 19:12 UTC, merged